change kbitem display in ticket (now with ajax)
TECLIB/glpi pull request #11
Opened 2016-12-08 13:18 UTC by orthagh

WIP don't merge

2016-12-09 06:40 UTC, trasher requested changes

2016-12-09 06:40 UTC, trasher commented on ajax/getDropdownValue.php
> +   $datastoadd = array();
`data` is invariable.

2016-12-09 06:40 UTC, trasher commented on inc/itilcategory.class.php
> +            $ret.= "</lebel>";
Typo

2016-12-09 06:40 UTC, trasher commented on inc/itilcategory.class.php
> +                     console.log('getKnowbaseItemAnswer');
Remove

2016-12-09 06:40 UTC, trasher commented on install/mysql/glpi-9.2-empty.sql
> +  `knowbaseitemcategories_id` int(11) NOT NULL DEFAULT '0',
I do not understand why a field is added here; or maybe PR description is no correct.

2016-12-09 08:07 UTC, orthagh commented on ajax/getDropdownValue.php
> +   $datastoadd = array();
yeah, in fact, it's not a part of this pr, juste a residual bug .
I can remove this part and fix it in upstream

2016-12-09 08:08 UTC, orthagh commented on inc/itilcategory.class.php
> +            $ret.= "</lebel>";
oh !

2016-12-09 08:08 UTC, orthagh commented on inc/itilcategory.class.php
> +                     console.log('getKnowbaseItemAnswer');
already done in local

2016-12-09 08:08 UTC, orthagh commented on install/mysql/glpi-9.2-empty.sql
> +  `knowbaseitemcategories_id` int(11) NOT NULL DEFAULT '0',
for recall: "WIP don't merge".
Some part are not finished

2016-12-09 13:22 UTC, orthagh commented
@trasher work done and description updated, you can review.

2016-12-21 12:50 UTC, orthagh commented
@trasher this branch is now rebased .

Could you check it ?

2016-12-21 13:21 UTC, trasher commented on install/mysql/glpi-9.2-empty.sql
> +  `knowbaseitemcategories_id` int(11) NOT NULL DEFAULT '0',
I still do not understand :)

2016-12-21 13:25 UTC, trasher commented on install/mysql/glpi-9.2-empty.sql
> +  `knowbaseitemcategories_id` int(11) NOT NULL DEFAULT '0',
OK sounds like this permit to do something that was not possible before.. Ok for me.

2016-12-21 13:38 UTC, trasher approved these changes

2016-12-21 13:43 UTC, merged